### ISSUE TITLE
关于QT

### ISSUE THREAD

**Issue by yty338** [calvinscofield/qt6-cpp#1]
作者大大，你的那个QT6.0的代码教程有无配套的视频讲解，如果有的话能把链接发我邮箱吗？2044053521@qq.com 如果没有请无视，打扰了

**Comment by calvinscofield** [comment]
> 作者大大，你的那个QT6.0的代码教程有无配套的视频讲解，如果有的话能把链接发我邮箱吗？[2044053521@qq.com](mailto:2044053521@qq.com) 如果没有请无视，打扰了

B站上有对这本书的视频讲解，分上下册，上册免费，下册收费，你可以参考一下。【《Qt6 C++开发指南 》2023（上册，完整版）】 https://www.bilibili.com/video/BV1km4y1k7CW/?p=85&share_source=copy_web
不过个人觉得看视频太慢，我是直接看书的，有任何问题都可以相互交流学习一下。
